version: "2"
services:
  ui:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      API_HOST: api
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb